### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [kleiton0x00/XSScope#11]
Hello,

When I run XSScope don't work. I follow the instruction of the github

```
[Fri Jan 15 08:54:17 2021] PHP 7.4.11 Development Server (http://localhost:1337) started
Exception in Tkinter callback                                                                       
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1885, in __call__
    return self.func(*args)
  File "/opt/XSScope/xsscope.py", line 1333, in start_xsscope
    tcp_server = str(tcp_server[6:])
TypeError: 'NgrokTunnel' object is not subscriptable
 
```
Any recomendation ?

A greeting and thanks

**Comment by kleiton0x00** [comment]
There seems to be an error with your Ngrok.
- Make sure you have Ngrok installed (not only in Xsscope directory, but also in /usr/bin PATH)
- Did you activate Ngrok (during setup.py by pasting the activation code)?
- Also make sure to restart the computer if the problem persists.

**Comment by GeneralBison** [comment]
I've also been having this problem, specifically on Kali.
Ngrok has installed sucessfully and I'm able to run it by itself, I've even tried copying the installed bin into the XSScope directory.

The issue is with the way that the program is attempting to substring tcp_server
![image](https://user-images.githubusercontent.com/2755919/167845034-1b85f7ac-339c-4d1b-bf42-da4c13c3308c.png)

EDIT: I'll also add that this is using Python 3.9.10, ngrok 2.3.40 and pyngrok 5.1.0 with XSScope installed as per the setup.sh script.

Maybe this worked using a previous version of any of these components but this is the current state as I can see it.

**Comment by GeneralBison** [comment]
What's the expected behaviour? Because looking at the code in its current state, `str(tcp_server)` gives you `NgrokTunnel: "tcp://<x>.tcp.ngrok.io:<port>" -> "localhost:1337"`, the IP address isn't returned at all.

**Comment by GeneralBison** [comment]
If what you actually want is the hostname, this would work:
```python
            tcp_server = str(tcp_server.public_url)
            tcp_server_host = str(tcp_server.split('/')[2]).split(':')[0]
            tcp_server_port = tcp_server.split(':')[2]
```

**Comment by kleiton0x00** [comment]
@GeneralBison thank you for showing the problem and introducing the solution as well. I managed to reproduce the issue and indeed there was an error in parsing and your solution works perfectly. The error happened because the software was developed before the new updates of both **Pyngrok** and **Ngrok**.
I updated the code to what you suggested :)

**Comment by GeneralBison** [comment]
Sorry I would have made a pull request but I've been really busy with work. Thanks for fixing!
